version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:00"
      timezone: "America/Vancouver"
    open-pull-requests-limit: 10
    assignees:
      - "BenRogersWPG"
