version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:30"
      timezone: "America/Vancouver"
    open-pull-requests-limit: 100
    assignees:
      - "BenRogersWPG"

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '15:30'
      timezone: "America/Vancouver"
    open-pull-requests-limit: 100
    assignees:
      - "BenRogersWPG"
