version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:30"
      timezone: "America/Vancouver"
    open-pull-requests-limit: 100
    cooldown:
      # Default cooldown for any dependency without a more specific SemVer-level rule below (falls back to 3 days if you omit this entirely).
      default-days: 5       
    assignees:
      - "BenRogersWPG"

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '15:30'
      timezone: "America/Vancouver"
    open-pull-requests-limit: 100
    cooldown:
      # Default cooldown for any dependency without a more specific SemVer-level rule below (falls back to 3 days if you omit this entirely).
      default-days: 5       
    assignees:
      - "BenRogersWPG"
